version: '3'

services:
  php:
    build: ./php-apache
    container_name: webapp
    ports:
      - 80:80
    volumes:
      - ./DocumentRoot:/var/www/html
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user
      

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
